version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ALLOWED_HOSTS=127.0.0.1,localhost,192.168.1.79,https://apple-school.herokuapp.com/,apple-school.herokuapp.com
      - SETTINGS=apple_school_project.settings.production
      - DEBUG=0

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "5000:5000"
    depends_on:
      - app
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  static_data: