version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./apple_school_project:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    command: sh -c "export DJANGO_SETTINGS_MODULE=apple_school_project.settings.development && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DEBUG=1