# Generated by Django 3.1.1 on 2022-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_school_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
