# Generated by Django 3.1.1 on 2022-05-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_school_website', '0002_eventmodel_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='downloads')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
    ]
